Finish OmniSharp manager, and did some clean up of configs

diff --git a/bin/bin/omnisharp-manager b/bin/bin/omnisharp-manager
--- a/bin/bin/omnisharp-manager
+++ b/bin/bin/omnisharp-manager
@@ -4,7 +4,7 @@
 # Works on: Linux, macOS & Cygwin/WSL
 
 usage() {
-    printf "usage: %s [-irVHu] [-v version] [-l location]\\n" "$0"
+    printf "usage: %s [-HMu] [-v version] [-l location]\\n" "$0"
 }
 
 # From: https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c
@@ -12,39 +12,25 @@ get_latest_version() {
     curl --silent "https://api.github.com/repos/OmniSharp/omnisharp-roslyn/releases/latest" |
     grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
 }
-get_current_version() {
-    # TODO implement this
-    printf "???"
-}
-
 
 # Options:
-# -i | install (will also update if already installed)
-# -r | remove
 # -v | version to use (otherwise use latest)
-# -V | print the version information
 # -l | where to install the server
 # -u | help / usage info
 # -H | install the HTTP version of the server
-# Options to add later:
 # -M | type of server: mono or regular
+# Options to add later:
 # -S | start the server (takes a solution file)
 
 location="$HOME/.omnisharp/"
 
-while getopts irv:Vl:uH o "$@"
+while getopts v:l:HMu o "$@"
 do
     case "$o" in
-        i)      install;;
-        r)      remove;;
         v)      version="$OPTARG";;
-        V)
-            printf "Latest version:    %s\\n" "$(get_latest_version)"
-            printf "Installed version: %s\\n" "$(get_current_version)"
-            exit 0
-            ;;
         l)      location="$OPTARG";;
         H)      http=".http";;
+        M)      mono=1;;
         u)      usage && exit 0;;
         [?])    usage && exit 1;;
     esac
@@ -52,31 +38,37 @@ done
 
 ext="tar.gz"
 
-case "$(uname -s)" in
-    "Linux")    os="linux";;
-    "Darwin")   os="osx";;
-    *)
-        if [ "$(uname -o)" = "Cygwin" ]; then
-            os="win"
-            ext="zip"
-            # TODO run post install: chmod +x $(find . -type f)
-        else
-            exit 1
-        fi
-        ;;
-esac
 case "$(uname -m)" in
     "x86_64")   machine="x64";;
     "i368")     machine="x86";;
     *)          exit 1;;
 esac
-file_name=$(printf "omnisharp%s-%s-%s.%s" "$http" "$os" "$machine" "$ext")
-
-if [ -z "$version" ]; then
-    version="$(get_latest_version)"
-fi
+case "$(uname -s)" in
+    "Linux")    os="linux-${machine}";;
+    "Darwin")   os="osx";;
+    *)
+        if [ "$(uname -o)" = "Cygwin" ]; then
+            os="win-${machine}"
+            ext="zip"
+        else
+            printf "Error: unknown system: %s\\n" "$(uname -s)"
+            exit 1
+        fi
+        ;;
+esac
+[ ! -z "$mono" ] && os="mono"
+file_name="omnisharp${http}-${os}.${ext}"
+[ -z "$version" ] && version="$(get_latest_version)"
 base_url="https://github.com/OmniSharp/omnisharp-roslyn/releases/download"
 full_url="${base_url}/${version}/${file_name}"
 echo "$full_url"
 
-# TODO Finish this
+rm -r "$location"
+mkdir -p "$location"
+curl -L "$full_url" -o "$location/$file_name"
+if [ "$ext" = "zip" ]; then
+    unzip "$location/$file_name" -d "$location/"
+    chmod +x $(find "$location" -type f)
+else
+    tar -zxvf "$location/$file_name" -C "$location/"
+fi
